#!/bin/bash
if [ -f /data/master ]; then
    # start a local controller 
    cd /home/indextank/nebu
    echo "Supervise's run starting supervisor."
    exec sudo -u indextank DJANGO_SETTINGS_MODULE=settings PYTHONPATH=../ /usr/bin/python supervisor.py 2>&1
    echo "Supervise's run (supervisor) ending."
else
    sleep 5
fi
