#!/bin/bash

# start a storage writer
cd /home/indextank/storage
echo "Supervise's run starting LogWriter server"
exec sudo -u indextank ionice -c 2 -n 3 /usr/bin/java -cp conf:lib/indextank-trunk-deps.jar:lib/indextank-trunk.jar com.flaptor.indextank.storage.LogWriterServer -p 15000 2>&1
