#!/bin/bash
# start a deploy manager
cd /home/indextank/nebu
echo "Supervise's run starting deploy manager."
exec sudo -u indextank DJANGO_SETTINGS_MODULE=settings PYTHONPATH=../ /usr/bin/python deploy_manager.py 2>&1
echo "Supervise's run (deploy manager) ending."
