#!/bin/bash
if [ -f /data/master ]; then
    # start a deploy manager
    cd /home/indextank/nebu
    echo "Supervise's run starting populator."
    exec sudo -u indextank DJANGO_SETTINGS_MODULE=settings PYTHONPATH=../ /usr/bin/python populator.py 2>&1
    echo "Supervise's run (populator) ending."
else
    sleep 5
fi
